sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-beamer
script:
- mkdir _build
- pdflatex -interaction=nonstopmode -halt-on-error -output-directory _build snips.tex
deploy:
  provider: releases
  api_key:
    secure:
    - $GITHUB_API_KEY
  file:
  - _build/snips.pdf
  skip_cleanup: true
  on:
    tags: true
env:
  matrix:
    secure: mUvKrVHQRPRWUgVRy2j0vb4eq0eCel51diAxgwqmxaRpwo7chEYsNwD5yDVm4LqAoV9j8oxYdUHC4SO/TZXUjCp+wHBbui+i3qZNji2uhU3/zijNey7FlXg2HBAjnHSPE34+kCWogBmRxhIKACG0Izs4KejM0iTDx3C8zU/SkgywF7/UC+dSL6yjvTCYFm0mbMrSJ1yWqM5+DE0abI23rEXBYNbF78ReMjGSZ/8u9FPnNAfvprLOrZZmcdyhIt9Unqpk89iZsJZS+QTYx1pp6mOX5IksYOxmY/ZUcTtNIqSStHViYod/oYAL3F4gPWs/EckVlVP9+bf153zjTCLxuYq9IV0KAuAADvKQHfa2byMjE3NifQ6KR+gCz8vGH5dBaiHaQv2gS55/z0izKM4zczu6Y/BA4bHijE6EKEMEdH+i/ll1ZmR4kVBbBzYCukssZwkeE4Fa972DQbROOXeerSYkw4uIXX+G1IGsTiff0mH2HMwyymaoqbtzW/spmb6M4zKtewLYKUCNAryVwz/iqLkRFQjvA3Ydg0TH8wQkrQRsDKr7VLdiqwZP/0/yRTqMdGkGwhZJVTp/8dC9XxTsXvX3TnjXLnXYmT7O8JDO45RGAD3asSTrFfvp2XH2VheapnBdZZ8TvTxBqUWCK+1qhTGxmdzerj4NsgA+/u1orpc=
